"""
Scheduled Task: Morning Briefing
Creates daily briefing document at 8:00 AM
"""
import json
from pathlib import Path
from datetime import datetime, timedelta

PROJECT_ROOT = Path(__file__).parent.parent.parent
VAULT_PATH = PROJECT_ROOT / 'AI_Employee_Vault'
if VAULT_PATH.is_symlink():
    VAULT_PATH = VAULT_PATH.resolve()


def count_files(folder: Path) -> int:
    """Count files in a folder"""
    if not folder.exists():
        return 0
    return len([f for f in folder.iterdir() if f.is_file() and not f.name.startswith('.')])


def get_priority_items(folder: Path, priority: str) -> list:
    """Get items with specific priority"""
    items = []
    if not folder.exists():
        return items

    for f in folder.glob('*.md'):
        content = f.read_text()
        if f'priority: {priority}' in content.lower() or f'priority:{priority}' in content.lower():
            # Extract title/subject
            for line in content.split('\n'):
                if line.startswith('# ') or line.startswith('## '):
                    items.append({'file': f.name, 'title': line.strip('# ')})
                    break
            else:
                items.append({'file': f.name, 'title': f.stem})

    return items


def get_yesterday_done() -> list:
    """Get items completed yesterday"""
    done_folder = VAULT_PATH / 'Done'
    if not done_folder.exists():
        return []

    yesterday = datetime.now() - timedelta(days=1)
    items = []

    for f in done_folder.glob('*.md'):
        # Check if modified yesterday
        mtime = datetime.fromtimestamp(f.stat().st_mtime)
        if mtime.date() == yesterday.date():
            items.append(f.name)

    return items


def create_morning_briefing():
    """Create morning briefing document"""
    timestamp = datetime.now()
    briefings_folder = VAULT_PATH / 'Briefings'
    briefings_folder.mkdir(exist_ok=True)

    # Gather data
    inbox_count = count_files(VAULT_PATH / 'Inbox')
    needs_action_count = count_files(VAULT_PATH / 'Needs_Action')
    pending_approval_count = count_files(VAULT_PATH / 'Pending_Approval')

    p1_items = get_priority_items(VAULT_PATH / 'Needs_Action', 'P1')
    p2_items = get_priority_items(VAULT_PATH / 'Needs_Action', 'P2')
    yesterday_done = get_yesterday_done()

    # Create briefing
    briefing_content = f'''---
type: briefing
generated: {timestamp.isoformat()}
period: {timestamp.strftime('%Y-%m-%d')}
---

# Morning Briefing - {timestamp.strftime('%A, %B %d, %Y')}

## Executive Summary
Good morning! Here's your daily briefing.

## Quick Stats
| Metric | Count |
|--------|-------|
| New in Inbox | {inbox_count} |
| Needs Action | {needs_action_count} |
| Awaiting Approval | {pending_approval_count} |
| Completed Yesterday | {len(yesterday_done)} |

## Priority Items

### 🔴 Critical (P1)
'''

    if p1_items:
        for item in p1_items[:5]:
            briefing_content += f"- [ ] {item['title']} ({item['file']})\n"
    else:
        briefing_content += "- No critical items. Great!\n"

    briefing_content += "\n### 🟡 High Priority (P2)\n"

    if p2_items:
        for item in p2_items[:5]:
            briefing_content += f"- [ ] {item['title']} ({item['file']})\n"
    else:
        briefing_content += "- No high priority items.\n"

    briefing_content += f'''
## Yesterday's Accomplishments
'''

    if yesterday_done:
        for item in yesterday_done[:10]:
            briefing_content += f"- ✅ {item}\n"
    else:
        briefing_content += "- No items completed yesterday.\n"

    briefing_content += f'''
## Recommended Actions Today
1. {'Process ' + str(inbox_count) + ' inbox items' if inbox_count > 0 else 'Inbox is clear'}
2. {'Review ' + str(pending_approval_count) + ' pending approvals' if pending_approval_count > 0 else 'No pending approvals'}
3. {'Handle ' + str(len(p1_items)) + ' critical items' if p1_items else 'No critical items to handle'}

---
*Generated by AI Employee: {timestamp.strftime('%Y-%m-%d %H:%M')}*
'''

    # Save briefing
    filename = f"BRIEFING_{timestamp.strftime('%Y-%m-%d')}.md"
    briefing_path = briefings_folder / filename
    briefing_path.write_text(briefing_content)

    # Also save to Inbox for visibility
    inbox_copy = VAULT_PATH / 'Inbox' / f"DAILY_BRIEFING_{timestamp.strftime('%Y-%m-%d')}.md"
    inbox_copy.write_text(briefing_content)

    print(f"[{timestamp}] Morning briefing created: {filename}")


if __name__ == '__main__':
    create_morning_briefing()
