"""
Scheduled Task: Weekly Report
Creates weekly summary report every Sunday
"""
import json
from pathlib import Path
from datetime import datetime, timedelta

PROJECT_ROOT = Path(__file__).parent.parent.parent
VAULT_PATH = PROJECT_ROOT / 'AI_Employee_Vault'
if VAULT_PATH.is_symlink():
    VAULT_PATH = VAULT_PATH.resolve()


def get_week_stats() -> dict:
    """Get statistics for the past week"""
    done_folder = VAULT_PATH / 'Done'
    logs_folder = VAULT_PATH / 'Logs'

    stats = {
        'completed_tasks': 0,
        'emails_processed': 0,
        'plans_created': 0,
        'approvals_handled': 0,
        'by_day': {}
    }

    week_ago = datetime.now() - timedelta(days=7)

    # Count completed tasks
    if done_folder.exists():
        for f in done_folder.glob('*.md'):
            mtime = datetime.fromtimestamp(f.stat().st_mtime)
            if mtime >= week_ago:
                stats['completed_tasks'] += 1

                day = mtime.strftime('%A')
                stats['by_day'][day] = stats['by_day'].get(day, 0) + 1

                if 'EMAIL' in f.name:
                    stats['emails_processed'] += 1

    # Count from logs
    for log_file in logs_folder.glob('*.json'):
        try:
            log_date = datetime.strptime(log_file.stem, '%Y-%m-%d')
            if log_date >= week_ago:
                with open(log_file, 'r') as f:
                    logs = json.load(f)
                    for entry in logs:
                        if entry.get('action_type') == 'plan_created':
                            stats['plans_created'] += 1
                        if 'approval' in entry.get('action_type', ''):
                            stats['approvals_handled'] += 1
        except:
            pass

    return stats


def create_weekly_report():
    """Create weekly summary report"""
    timestamp = datetime.now()
    reports_folder = VAULT_PATH / 'Reports'
    reports_folder.mkdir(exist_ok=True)

    week_start = timestamp - timedelta(days=7)
    stats = get_week_stats()

    report_content = f'''---
type: weekly_report
generated: {timestamp.isoformat()}
period: {week_start.strftime('%Y-%m-%d')} to {timestamp.strftime('%Y-%m-%d')}
---

# Weekly Report
## {week_start.strftime('%B %d')} - {timestamp.strftime('%B %d, %Y')}

## Executive Summary
This week your AI Employee processed **{stats['completed_tasks']} tasks**.

## Weekly Statistics

| Metric | Count |
|--------|-------|
| Tasks Completed | {stats['completed_tasks']} |
| Emails Processed | {stats['emails_processed']} |
| Plans Created | {stats['plans_created']} |
| Approvals Handled | {stats['approvals_handled']} |

## Activity by Day

| Day | Tasks Completed |
|-----|-----------------|
'''

    days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    for day in days_order:
        count = stats['by_day'].get(day, 0)
        bar = '█' * min(count, 20)
        report_content += f"| {day} | {count} {bar} |\n"

    # Current status
    inbox_count = len(list((VAULT_PATH / 'Inbox').glob('*.md'))) if (VAULT_PATH / 'Inbox').exists() else 0
    needs_action_count = len(list((VAULT_PATH / 'Needs_Action').glob('*.md'))) if (VAULT_PATH / 'Needs_Action').exists() else 0

    report_content += f'''
## Current Status

- **Inbox**: {inbox_count} items pending
- **Needs Action**: {needs_action_count} items pending

## Recommendations for Next Week

'''

    if needs_action_count > 20:
        report_content += "1. ⚠️ High backlog in Needs_Action - consider processing more items\n"
    if stats['completed_tasks'] < 10:
        report_content += "1. 📈 Task completion was low - review if watchers are running\n"
    if stats['completed_tasks'] >= 10:
        report_content += "1. ✅ Good productivity this week - keep it up!\n"

    report_content += f'''
---
*Weekly Report generated by AI Employee: {timestamp.strftime('%Y-%m-%d %H:%M')}*
'''

    # Save report
    filename = f"WEEKLY_REPORT_{timestamp.strftime('%Y-%m-%d')}.md"
    report_path = reports_folder / filename
    report_path.write_text(report_content)

    print(f"[{timestamp}] Weekly report created: {filename}")


if __name__ == '__main__':
    create_weekly_report()
